=== ShamimsJava/Advance-Java/xmlProject/src/classWork/StudentList.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT studentList (student)*>
<!ELEMENT student (id|name|age|email|address)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address EMPTY>

=== ShamimsJava/Advance-Java/xmlProject/src/classWork/StudentList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentList SYSTEM "StudentList.dtd">
<studentList>
    <student>
        <id>101</id>
        <name>Shamim</name>
        <age>26</age>
        <email>shamimsjava@gmail.com</email>
        <address></address>
    </student>
    <student>
        <id>102</id>
        <name>Sarker</name>
        <age>26</age>
        <email>shamimjava@gmail.com</email>
        <address></address>
    </student>
</studentList>
